sudo: false
language: php
branches:
  only:
  - "/^v\\d.*$/"
  - master
  - development
php:
- 5.6
- 7.1
env:
  matrix:
  - WP_VERSION=4.4
  - WP_VERSION=latest
  - WP_VERSION=trunk
before_install:
- composer global require "squizlabs/php_codesniffer=*"
- composer global require "wp-coding-standards/wpcs"
- ls ${HOME}/.composer/vendor/squizlabs/php_codesniffer/bin
- "${HOME}/.composer/vendor/squizlabs/php_codesniffer/bin/phpcs --config-set installed_paths
  ~/.composer/vendor/wp-coding-standards/wpcs"
- phpenv rehash;
script:
- "${HOME}/.composer/vendor/squizlabs/php_codesniffer/bin/phpcs --standard=WordPress-Core
  --extensions=php --colors -s -p -v ./"
before_deploy:
- npm install
- grunt build
deploy:
  provider: releases
  api_key:
    secure: GKKvidCupek2S+xiI1PARC1LVFOA/khV/ncgz8UdDAcGNA5n62tA1hMAJHbYhUmYU0SUgrSxfinsJoBZhhhPnXf2EGC/hHa9HW91FL8xIs/VTBE624lTYB1yFL8QrW2oTrSJsN1AK9cxZfeYA840PtZlqk+PaArGqDp6d+phwbOdaIrUXtlFYIQBLWPu30DdIlE5VzrNo830ZbnSCGuziGpTGA2Z9xNOK9vKoDkGdaaycwEPCrWHPX+NebrlUFuV95y2j5S15bPlpbvvjnky8TufnkrOOSsqHwpOjKsDqlMMSvuZWj8rnoRuhulzcvZpdIIGQX3VOfVhlZvKGWDwulXPOmRvgDglbJzy8nxoNGzm+x8uNpej1j9/PMkw0SDzA6OjBhyIJSX/pyNCvLJk12S5wDhq75rKz+Gxv0UH8n5RwAuWautteCZwIcd4WcwuyoPE7h3n78TLlvFIWRhYsnxZFo+EYvLWSJHxeFXbYdHzs33w3vu1FZBNebX9CrquYtxA2kAb/BD8xJHrSch24ppFFiQuCygOYPA++KlGzge1b2cg6nME/roIxvR9z40r6k/rnRxK2rP5fG0I2jGTaGVqx/vdseCFLbGdMXoEpfTFGwgXvE1c5T8Rhixsg20NIJMpPk7Jp95kk+rGecWZbv5vFs4YX4pxrJoQ36Faass=
  file_glob: true
  file: build/wp-monitor-*.zip
  on:
    repo: brothman01/wp-monitor
    tags: true
    php: '7.1'
    condition: "$WP_VERSION=trunk"
  skip_cleanup: true
  overwrite: true
